# Site settings
theme: minima
title: Data and other big ideas
email: antti.loukiala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Every now and then you come up with neat ideas and 
  every now and then you want to share them.
  This is some of my ideas to spread.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aloukiala
github_username:  aloukiala

# Build settings
markdown: kramdown
